export const GET_STUDENT_DETAILS = "GET_STUDENT_DETAILS";
export const GET_QUERIES = "GET_QUERIES";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const GET_BONAFIDE_STATUS = "GET_BONAFIDE_STATUS";
// Faculty

export const GET_ELECTIVE_CATEGORY_LIST = "GET_ELECTIVE_CATEGORY_LIST";

//Student Section

export const GET_STUDENTSECTION_QUERIES = "GET_STUDENTSECTION_QUERIES";
