export const GET_STUDENT_DETAILS = "GET_STUDENT_DETAILS";
export const GET_QUERIES = "GET_QUERIES";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const GET_BONAFIDE_STATUS = "GET_BONAFIDE_STATUS";
// Faculty

export const GET_ELECTIVE_CATEGORY_LIST = "GET_ELECTIVE_CATEGORY_LIST";
export const GET_LC_STATUS = "GET_LC_STATUS";

//Student Section
export const GET_FEERECEIPT_STATUS = "GET_FEERECEIPT_STATUS";
export const GET_LC_REQUESTS = "GET_LC_REQUESTS";
export const GET_STUDENTSECTION_QUERIES = "GET_STUDENTSECTION_QUERIES";
export const UPDATE_LC_REQUEST = "UPDATE_LC_REQUEST";
